<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GymCore.Infrastructure</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymCore.Application\GymCore.Application.vbproj" />
    <ProjectReference Include="..\GymCore.Domain\GymCore.Domain.vbproj" />
  </ItemGroup>

</Project>
